TranNgocTan_Tuan4/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TranNgocTan_Tuan4.Models
{
    public class GioHang
    {
        MyDataDataContext data = new MyDataDataContext();
        public int masach { get; set; }

        [Display(Name = "Tên sách")]
        public string tensach { get; set; }

        [Display(Name = "Ảnh bìa")]
        public string hinh { get; set; }
        [Display(Name = "Giá bán")]
        public Double giaban { get; set; }
        [Display(Name = "Số lượng")]
        public int iSoluong { get; set; }
        [Display(Name = "Thành tiền")]
        public Double dThanhtien {
            get { return iSoluong * giaban; }
        }
        public GioHang(int id)
        {
            masach = id;
            Sach sach = data.Saches.Single(n => n.masach == masach);
            tensach = sach.tensach;
            hinh = sach.hinh;
            giaban = double.Parse(sach.giaban.ToString());
            iSoluong = 1;
        }

    }
}

TranNgocTan_Tuan4/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranNgocTan_Tuan4.Models;

namespace TranNgocTan_Tuan4.Controllers
{
    public class GioHangController : Controller
    {
        MyDataDataContext data = new MyDataDataContext();
        public List<GioHang> Laygiohang()
        {
            List<GioHang> lstGiohang = Session["GioHang"] as List<GioHang>;
            if(lstGiohang == null)
            {
                lstGiohang = new List<GioHang>();
                Session["GioHang"] = lstGiohang;

            }
            return lstGiohang;
        }
        // GET: GioHang
        public ActionResult ThemGioHang(int id, string strURL)
            
        {
            List<GioHang> lstGiohang = Laygiohang();
            GioHang sanpham = lstGiohang.Find(n => n.masach == id);
            if(sanpham == null)
            {
                sanpham = new GioHang(id);
                lstGiohang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoluong++;
                return Redirect(strURL);
            }
            
        }
        private int TongSoLuong()
        {
            int tsl = 0;
            List<GioHang> lstGiohang = Session["GioHang"] as List<GioHang>;
            if(lstGiohang != null)
            {
                tsl = lstGiohang.Sum(n => n.iSoluong);
            }
            return tsl;
        }
        private int TongSoLuongSanPham()
        {
            int tsl = 0;
            List<GioHang> lstGiohang = Session["GioHang"] as List<GioHang>;
            if (lstGiohang != null)
            {
                tsl = lstGiohang.Count;
            }
            return tsl;
        }
        private double TongTien()
        {
            double tt = 0;
            List<GioHang> lstGiohang = Session["GioHang"] as List<GioHang>;
            if (lstGiohang != null)
            {
                tt = lstGiohang.Sum(n => n.dThanhtien);
            }
            return tt;
        }

        public ActionResult GioHang()
        {
            List<GioHang> lstGiohang = Laygiohang();
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return View(lstGiohang);
        }

        public ActionResult GioHangPartial()
        {
            
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            ViewBag.Tongsoluongsanpham = TongSoLuongSanPham();
            return PartialView();
        }

        public ActionResult XoaGioHang(int id)
        {
            List<GioHang> lstGiohang = Laygiohang();
            GioHang sanpham = lstGiohang.SingleOrDefault(n => n.masach == id);
            if(sanpham != null)
            {
                lstGiohang.RemoveAll(n => n.masach == id);
                return RedirectToAction("GioHang");
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult CapNhatGioHang(int id, FormCollection collection)
        {
            List<GioHang> lstGiohang = Laygiohang();
            GioHang sanpham = lstGiohang.SingleOrDefault(n => n.masach == id);
            if (sanpham != null)
            {
                sanpham.iSoluong = int.Parse(collection["txtSoLg"].ToString());
                
            }
            return RedirectToAction("GioHang");
        }

        public ActionResult XoaTatCaGioHang(int id)
        {
            List<GioHang> lstGiohang = Laygiohang();
            lstGiohang.Clear();
            return RedirectToAction("GioHang");
        }

        [HttpGet]
        public ActionResult DatHang()
        {
            if (Session["Giohang"] == null)
            {
                return RedirectToAction("Index", "Fashion");
            }
            List<GioHang> gioHangs = Laygiohang();
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();

            return View(gioHangs);
        }
        [HttpPost]
        public ActionResult DatHang(FormCollection collection)
        {
            DonHang dONDATHANG = new DonHang();
            KhachHang kh = (KhachHang)Session["TaiKhoan"];
            Sach s = new Sach();
            List<GioHang> gioHangs = Laygiohang();
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["NgayGiao"]);

            dONDATHANG.makh = kh.makh;
            dONDATHANG.ngaydat = DateTime.Now;
            dONDATHANG.ngaygiao = DateTime.Parse(ngaygiao);
            dONDATHANG.giaohang = false;
            dONDATHANG.thanhtoan = false;

            data.DonHangs.InsertOnSubmit(dONDATHANG);
            data.SubmitChanges();
            foreach (var item in gioHangs)
            {
                ChiTietDonHang CT = new ChiTietDonHang();

                CT.madon = dONDATHANG.madon;
                CT.masach = item.masach;
                CT.soluong = item.iSoluong;
                CT.gia = (decimal)item.giaban;
                s = data.Saches.Single(n => n.masach == item.masach);
                s.soluongton -= CT.soluong;
                data.SubmitChanges();
                data.ChiTietDonHangs.InsertOnSubmit(CT);
            }
            data.SubmitChanges();
            Session["Giohang"] = null;
            return RedirectToAction("XacNhanDonHang", "Giohang");

        }

        public ActionResult XacnhanDonhang()
        {
            return View();
        }




    }
}

TranNgocTan_Tuan4/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TranNgocTan_Tuan4.Models;

namespace TranNgocTan_Tuan4.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult ListSach()
        {
            var all_sach = from ss in data.Saches select ss;
            return View(all_sach);
        }
        public ActionResult Detail(int id)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            return View(D_sach);
        }
        public ActionResult Create()
        {
            return View();

        }
        

        [HttpPost]
        public ActionResult Create(FormCollection collection, Sach s)
        {
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                s.tensach = E_tensach.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_giaban;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                data.Saches.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            return View(E_sach);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.Saches.First(m => m.masach == id);
            var E_tensach = collection["tensach"];
            var E_hinh = collection["hinh"];
            var E_giaban = Convert.ToDecimal(collection["giaban"]);
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycatnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            E_sach.masach = id;
            if (string.IsNullOrEmpty(E_tensach))
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                E_sach.tensach = E_tensach;
                E_sach.hinh = E_hinh;
                E_sach.giaban = E_giaban;
                E_sach.ngaycapnhat = E_ngaycapnhat;
                E_sach.soluongton = E_soluongton;
                UpdateModel(E_sach);
                data.SubmitChanges();
                return RedirectToAction("ListSach");
            }
            return this.Edit(id);
        }

        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "" ;
            }
            file.SaveAs(Server.MapPath("~/ Content / images /" +file.FileName));
            return "/ Content / images / "+file.FileName;
        }
        //-----------------------------------------
        public ActionResult Delete(int id)
        {
            var D_sach = data.Saches.First(m => m.masach == id);

        
        return View(D_sach);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.Saches.Where(m => m.masach == id).First();
            data.Saches.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("ListSach");
        }
    }
}

TranNgocTan_Tuan4/Views/GioHang/DatHang.cshtml
@model IEnumerable<TranNgocTan_Tuan4.Models.GioHang>
@using TranNgocTan_Tuan4.Models
@{
    ViewBag.Title = "DatHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DatHang</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.masach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tensach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.hinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.giaban)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iSoluong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dThanhtien)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.masach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tensach)
            </td>
            <td>
                <img src="@item.hinh" width="180" />
            </td>
            @using (Html.BeginForm("CapNhatGioHang", "Giohang", new { @id = item.masach }))
            {
                <td>
                    @String.Format("{0:0,0}", item.giaban) VND
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.iSoluong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dThanhtien)
                </td>
            }
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
    <tr style="font-weight:bold; text-align:left; color:red">
        <td colspan="3">Số loại sách: @ViewBag.Tongluongsanpham</td>
        <td colspan="4">Số lượng sách: @ViewBag.Tốngluong</td>
        <td colspan="5">Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien)</td>
    </tr>
    <tr style="font-weight: bold; color: blue; text-align:right">
        <td colspan="6">
            @Html.ActionLink("Trở vê giỏ hàng", "Giohang", "GioHang")
        </td>
    </tr>
</table>
<h2 style="text-align:center">Thông tin đặt hàng !</h2>
@{
    KhachHang kh = (KhachHang)Session["TaiKhoan"];
}
<table align="center">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <tr style="height:40px">
            <td>Họ tên khách hàng: </td>
            <td style="font-weight:bold">@kh.hoten</td>
        </tr>
        <tr style="height:40px">
            <td>Email: </td>
            <td style="font-weight:bold">@kh.email</td>
        </tr>
        <tr style="height:40px">
            <td>Địa chỉ: </td>
            <td style="font-weight:bold">@kh.diachi</td>
        </tr>
        <tr style="height:40px">
            <td>Điện thoại: </td>
            <td style="font-weight:bold">@kh.dienthoai</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày đặt: </td>
            <td style="font-weight:bold">@DateTime.Now.ToShortDateString()</td>
        </tr>
        <tr style="height:40px">
            <td>Ngày giao: </td>
            <td style="font-weight:bold">
                <input type="date" name="NgayGiao" />
            </td>
        </tr>
        <tr style="height:40px">
            <td>Họ tên khách hàng: </td>
            <td style="font-weight:bold">
                <input type="submit" value="Xác nhận" class="btn btn-success" />
            </td>
        </tr>
    }

</table>

TranNgocTan_Tuan4/Views/GioHang/GioHang.cshtml
@model IEnumerable<TranNgocTan_Tuan4.Models.GioHang>

@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Gio hang</h2>


<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.tensach) </th>
        <th>@Html.DisplayNameFor(model => model.hinh) </th>
        <th>@Html.DisplayNameFor(model => model.giaban) </th>
        <th>@Html.DisplayNameFor(model => model.iSoluong) </th>
        <th>@Html.DisplayNameFor(model => model.dThanhtien) </th>
        <th></th>
        <th></th>


    </tr>

    @foreach (var item in Model)
    {
                <tr>
                    <td> @Html.DisplayFor(modelItem => item.tensach) </td>
                    <td><img src="@item.hinh" width="180" /></td>
                    @using (Html.BeginForm("CapnhatGioHang", "GioHang", new { @id = item.masach }))
                {
                    <td> @String.Format("{0:0,0}", item.giaban) VNĐ </td>
                    <td><input type="number" min="1" name="txtSoLg" value="item.iSoluong" /></td>
                    <td> @Html.DisplayFor(modelItem => item.dThanhtien)</td>
                    <td> <a href="@Url.Action("Detail","Sach", new { id = item.masach })">Chi tiet</a> 
                    | @Html.ActionLink("Xoa", "XoaGioHang", new { @id = item.masach})
                    </td> 
                    <td><input type="submit" value="Cap nhat" class="btn btn-success" /></td>

                }
                </tr>
            }
<tr style="font-weight:bold; text-align:left; color:red">
    <td colspan="2"> So loai sach: @ViewBag.Tongsoluongsanpham</td>
    <td colspan="2"> So luong sach: @ViewBag.Tongsoluong</td>
    <td colspan="4"> Tong tien: @String.Format("{0:0,0}",ViewBag.Tongtien) VNĐ </td>

</tr>

    <tr style="font-weight:bold; color:blue; text-align:right ">
        <td colspan="5">
            @Html.ActionLink("Xoa gio hang", "XoaTatCaGioHang")

        </td>

    </tr>
    <tr style="font-weight:bold; color:yellow; text-align:right">
        <td colspan="5">
            @Html.ActionLink("Dat hang", "Dathang", "GioHang")

        </td>

    </tr>
</table>

TranNgocTan_Tuan4/Views/GioHang/GioHangPartial.cshtml
<a class="getstarted scrollto active" href="@Url.Action("GioHang",
"GioHang")" style="font-weight:bold; text-decoration:none">
    Giỏ hàng (@ViewBag.Tongsoluongsanpham)
</a>

TranNgocTan_Tuan4/Views/GioHang/XacnhanDonhang.cshtml
@{
    ViewBag.Title = "XacnhanDonhang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>XacnhanDonhang</h2>
<h2>Đơn hàng đã được xác nhận</h2>
<h3>Chúng tôi sẽ giao hàng cho bạn sớm nhất có thể !</h3>
<p>
    @Html.ActionLink("Về trang chủ", "Index", "Home")
</p>